import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1050}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:4173/demo');await page.getByRole('heading',{name:'Boulder Foothills Loop'}).waitFor();await page.locator('.maplibregl-canvas').waitFor();await page.waitForTimeout(1600);await page.screenshot({path:'/tmp/paceline-desktop.png',fullPage:true});assert.equal(await page.locator('.station-row').count(),5);
await page.getByRole('checkbox').uncheck();assert.equal(await page.locator('.map-marker.estimated').count(),0);
await page.setViewportSize({width:390,height:844});await page.screenshot({path:'/tmp/paceline-mobile.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
await page.goto('http://127.0.0.1:4173/setup');await page.getByLabel('Race name',{exact:true}).fill('Test race');await page.getByLabel('Start date & time').fill('2026-09-20T06:00');await page.getByLabel('Garmin KML feed URL',{exact:false}).fill('https://share.garmin.com/Feed/Share/test');await page.locator('input[type=file]').setInputFiles({name:'test.gpx',mimeType:'application/gpx+xml',buffer:Buffer.from('<gpx><trk><trkseg><trkpt lat="40" lon="-105"/><trkpt lat="40.01" lon="-105.01"/><trkpt lat="40.02" lon="-105.02"/></trkseg></trk></gpx>')});await page.getByLabel('Name',{exact:true}).fill('Joder Aid');await page.getByLabel('Distance (mi)').fill('1.2');await page.getByRole('button',{name:'Add aid station'}).click();await page.getByText('1.20 mi from start').waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'/tmp/paceline-editor-mobile.png',fullPage:true});
await page.getByRole('button',{name:'Create race & private links'}).click();await page.getByRole('alert').waitFor();
// A previously visited viewer survives a cold offline reload through the SW shell.
await page.goto('http://127.0.0.1:4173/demo');await page.evaluate(()=>navigator.serviceWorker.ready);await page.waitForTimeout(1000);await context.setOffline(true);await page.reload();await page.getByRole('heading',{name:'Boulder Foothills Loop'}).waitFor();await page.getByText('You’re offline.',{exact:false}).waitFor();await page.screenshot({path:'/tmp/paceline-offline.png',fullPage:true});assert.deepEqual(errors,[]);await browser.close();console.log('PASS: desktop/mobile, GPX upload, aid stations, estimate toggle, missing-config error, offline reload; no runtime exceptions.');
