import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {readFileSync, writeFileSync} from 'node:fs';
const path='dist/client/firebase-config.json', original=readFileSync(path);
const id=crypto.randomUUID(), now=Date.now();
const endpoint=`http://127.0.0.1:9000/races/${id}.json?ns=demo-paceline`;
const headers={Authorization:'Bearer owner','Content-Type':'application/json'};
const route=Array.from({length:6000},(_,i)=>[-105+i*.00001,40+Math.sin(i/1000)*.001]);
const race={id,name:'Offline regression',startAt:now-3600000,route,distances:route.map((_,i)=>i*.001),elevationsM:route.map((_,i)=>1000+i*.1),stations:[{id:'finish',name:'Finish line',km:5.999}],status:'live',progressKm:1,fix:{lng:route[1000][0],lat:route[1000][1],at:now,km:1},revision:1,heartbeatAt:now,feedOk:true};
await fetch(endpoint,{method:'PUT',headers,body:JSON.stringify(race)});
writeFileSync(path,JSON.stringify({apiKey:'demo-key',projectId:'demo-paceline',appId:'demo-app',databaseURL:'https://demo-paceline.firebaseio.com',emulator:true}));
const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
try {
 const c=await b.newContext(),p=await c.newPage();
 let frames=[];p.on('websocket',ws=>ws.on('framereceived',e=>frames.push(String(e.payload))));
 await p.goto('http://127.0.0.1:4173/r/'+id);
 await p.getByRole('heading',{name:race.name}).waitFor();
 await p.locator('.map-marker.estimated').waitFor();
 await p.evaluate(()=>{window.marker=document.querySelector('.map-marker.estimated');window.aid=document.querySelector('.map-marker.aid');});
 await p.waitForTimeout(2100);
 assert.ok(await p.evaluate(()=>window.marker===document.querySelector('.map-marker.estimated') && window.aid===document.querySelector('.map-marker.aid')));
 frames=[];await fetch(endpoint,{method:'PATCH',headers,body:JSON.stringify({heartbeatAt:now+60000})});
 await p.waitForTimeout(600);
 assert.ok(frames.join('').length<10000, 'Heartbeat should not resend route geometry');
 await p.evaluate(()=>navigator.serviceWorker.ready);
 await p.waitForFunction(()=>new Promise(resolve=>{const r=indexedDB.open('milemark-offline',1);r.onsuccess=()=>{const q=r.result.transaction('races').objectStore('races').count();q.onsuccess=()=>{resolve(q.result>0);r.result.close();};};}));
 await c.setOffline(true);await p.close();
 const cold=await c.newPage();await cold.goto('http://127.0.0.1:4173/r/'+id);
 await cold.getByRole('heading',{name:race.name}).waitFor();await cold.waitForTimeout(700);
 assert.doesNotMatch(await cold.locator('body').innerText(),/Failed to fetch/);
 await c.setOffline(false);await fetch(endpoint,{method:'PATCH',headers,body:JSON.stringify({name:'Reconnected successfully'})});
 await cold.getByRole('heading',{name:'Reconnected successfully'}).waitFor({timeout:20000});
 const setup=await c.newPage();await setup.goto('http://127.0.0.1:4173/setup');
 const points=Array.from({length:16000},(_,i)=>`<trkpt lat="${40+i*.000001}" lon="${-105+Math.sin(i/100)*.001}">${i===100?'':`<ele>${1000+Math.sin(i/100)*30}</ele>`}</trkpt>`).join('');
 await setup.locator('input[type=file]').setInputFiles({name:'large.gpx',mimeType:'application/gpx+xml',buffer:Buffer.from(`<gpx><trk><trkseg>${points}</trkseg></trk></gpx>`)});
 await setup.getByText('total elevation gain · from GPX',{exact:false}).waitFor();
 assert.doesNotMatch(await setup.locator('body').innerText(),/Please simplify|Elevation data unavailable/);
 console.log('PASS: real-race cold offline load, IndexedDB storage, reconnection, small heartbeat frames, stable markers, and 16,000-point GPX with elevation gaps.');
} finally {await b.close();writeFileSync(path,original);await fetch(endpoint,{method:'DELETE',headers});}
